name: "godot-ci export"
on:
  push:
    tags: ["*"]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: Savor-22b
  PROJECT_PATH: frontend/Savor-22b

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:mono-4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          submodules: true


      - name: Add safe.directory configuration
        run: |
          REPO_PATH=$(pwd)
          echo "Repository path is $REPO_PATH"
          git config --global --add safe.directory $REPO_PATH

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows


  export-mac:
    name: Mac Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:mono-4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          submodules: true


      - name: Add safe.directory configuration
        run: |
          REPO_PATH=$(pwd)
          echo "Repository path is $REPO_PATH"
          git config --global --add safe.directory $REPO_PATH

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Mac OSX" ../build/mac/$EXPORT_NAME.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: mac
          path: build/mac
